prof-freedson/pi-borasio

package-lock.json, package.json, src/app/motorista/page.tsx
=> atualização total

src/app/api/chat/route.ts
- Impede datas inválidas (ex: 32/15/2025, mês 13, dia 0)
- Impede horários impossíveis (ex: 25:61)
- Bloqueia agendamentos no passado ou muito distantes
- Pede confirmação em casos de datas ambíguas
- Mantém tom simpático e acolhedor do Vitorino
=> feat(prompt): validação de datas

src/app/components/ChatFlutuante.tsx
Alteração:
Foram ajustadas as cores do chat flutuante para melhorar a identidade visual e a experiência do usuário. As mudanças focam apenas em aspectos de estilo, sem alterar a lógica ou o funcionamento do componente.
___SamReis007____
=> style(chat): ajustar cores do chat flutuante

package.json, src/app/feedback/page.tsx, src/app/usuario/page.tsx
feat(routes) criação da rota feedback e alterações em algumas páginas
=> feat(routes) criação da rota feedback e alterações em algumas páginas

frontend/src/app/api/recuperar-senha/route.ts, frontend/src/app/api/resetar-senha/route.ts, frontend/src/app/components/Header.tsx, frontend/src/app/components/RecuperarSenhaForm.tsx, frontend/src/app/components/ResetarSenhaForm.tsx, frontend/src/app/recuperar-senha/page.tsx, frontend/src/app/resetar-senha/page.tsx, package-lock.json
para recuperação e redefinição de senha
=> feat(auth): adiciona rotas e formulários

backend/src/main/java/com/borasio_back/backend/repository/AvaliacaoRepository.java, backend/src/main/java/com/borasio_back/backend/repository/CorridaRepository.java, backend/src/main/java/com/borasio_back/backend/repository/MotoristaRepository.java, backend/src/main/java/com/borasio_back/backend/repository/PagamentoRepository.java, backend/src/main/java/com/borasio_back/backend/repository/PassageiroRepository.java, backend/src/main/java/com/borasio_back/backend/repository/UsuarioRepository.java, backend/src/main/java/com/borasio_back/backend/service/AuthService.java, backend/src/main/java/com/borasio_back/backend/service/AvaliacaoService.java, backend/src/main/java/com/borasio_back/backend/service/CorridaService.java, backend/src/main/java/com/borasio_back/backend/service/PagamentoService.java, backend/src/main/java/com/borasio_back/backend/service/UsuarioService.java
🗂️ Função de cada arquivo dentro de repository
UsuarioRepository.java
Responsável por manipular os dados da entidade Usuario.
Vai permitir salvar novos usuários, buscar usuários existentes e até criar buscas personalizadas, como encontrar por e-mail ou CPF.
Será fundamental para autenticação e gerenciamento de perfis.
PassageiroRepository.java
Voltado para a entidade Passageiro.
Permitirá recuperar passageiros cadastrados, verificar informações de cadastro e dar suporte às operações ligadas a corridas feitas pelos passageiros.
MotoristaRepository.java
Cuidará da persistência da entidade Motorista.
Permitirá, por exemplo, encontrar motoristas disponíveis, buscar por CNH e vincular motoristas às corridas.
CorridaRepository.java
Manipula os registros de corridas (Corrida).
Possibilitará …
=> feat(repository): add repositories

frontend/src/app/api/recuperar-senha/route.ts, frontend/src/app/api/resetar-senha/route.ts, frontend/src/app/components/Header.tsx, frontend/src/app/components/RecuperarSenhaForm.tsx, frontend/src/app/components/ResetarSenhaForm.tsx, frontend/src/app/pessoal/login/page.tsx, frontend/src/app/pessoalmotorista/loginmotorista/page.tsx, frontend/src/app/recuperar-senha/page.tsx, frontend/src/app/resetar-senha/page.tsx
feat(routes) Alteração nas rotas de recuperar e resetar a senha
=> feat(routes) Alteração nas rotas de recuperar e resetar a senha

backend/src/main/java/com/borasio_back/backend/dto/AuthRequest.java, backend/src/main/java/com/borasio_back/backend/dto/AuthResponse.java, backend/src/main/java/com/borasio_back/backend/dto/AvaliacaoDTO.java, backend/src/main/java/com/borasio_back/backend/dto/CorridaDTO.java, backend/src/main/java/com/borasio_back/backend/dto/CorridaRequest.java, backend/src/main/java/com/borasio_back/backend/dto/PagamentoDTO.java, backend/src/main/java/com/borasio_back/backend/dto/UsuarioDTO.java, backend/src/main/java/com/borasio_back/backend/enums/Role.java, backend/src/main/java/com/borasio_back/backend/enums/StatusCorrida.java, backend/src/main/java/com/borasio_back/backend/enums/StatusPagamento.java, backend/src/main/java/com/borasio_back/backend/enums/TipoAcessibilidade.java, backend/src/main/java/com/borasio_back/backend/enums/TipoEvento.java, backend/src/main/java/com/borasio_back/backend/exception/BusinessException.java, backend/src/main/java/com/borasio_back/backend/exception/GlobalExceptionHandler.java, backend/src/main/java/com/borasio_back/backend/exception/ResourceNotFoundException.java
Adicionei a estrutura fundamental para o projeto com as seguintes implementações:
DTOs (Data Transfer Objects): Criei classes para transferência de dados entre as camadas, incluindo AuthRequest, AuthResponse, UsuarioDTO, CorridaDTO, PagamentoDTO e AvaliacaoDTO, garantindo uma separação clara entre as entidades de domínio e os objetos de transferência.
Enums: Implementei enums para padronizar os status e tipos do sistema, como Role, StatusCorrida, StatusPagamento, TipoAcessibilidade e TipoEvento, proporcionando maior consistência e segurança nos dados.
Exceptions: Desenvolvi exceções customizadas (ResourceNotFoundException e BusinessException) junto com um GlobalExceptionHandler para tratamento centralizado de erros, melhorando a experiência de debug e a resposta da API.
Esta implementação …
=> feat: implementar estrutura base de DTOs, enums e exceptions

frontend/src/app/components/ResetarSenhaForm.tsx
de redefinição de senha com ícones e bordas coloridas
=> feat(ui): aprimora feedback visual de erro e sucesso no formulário

frontend/src/app/components/ResetarSenhaForm.tsx
aprimorado no formulário de redefinição de senha
=> feat(auth): validação de força da senha e feedback visual 

backend/src/main/java/com/borasio_back/backend/controller/MotoristaController.java, backend/src/main/java/com/borasio_back/backend/controller/PassageiroController.java, backend/src/main/java/com/borasio_back/backend/controller/PasswordRecoveryController.java, backend/src/main/java/com/borasio_back/backend/controller/UsuarioController.java, backend/src/main/java/com/borasio_back/backend/dto/MotoristaDTO.java, backend/src/main/java/com/borasio_back/backend/dto/PassageiroDTO.java, backend/src/main/java/com/borasio_back/backend/model/entity/Motorista.java, backend/src/main/java/com/borasio_back/backend/model/entity/Passageiro.java, backend/src/main/java/com/borasio_back/backend/repository/MotoristaRepository.java, backend/src/main/java/com/borasio_back/backend/repository/PassageiroRepository.java, backend/src/main/java/com/borasio_back/backend/repository/UsuarioRepository.java, backend/src/main/java/com/borasio_back/backend/service/MotoristaService.java, backend/src/main/java/com/borasio_back/backend/service/PassageiroService.java, backend/src/main/java/com/borasio_back/backend/service/UsuarioService.java
"fix(routes) API passageiro e motorista funcionando..."
=> "fix(routes) API passageiro e motorista funcionando..."

frontend/src/app/admin/passageiros/page.tsx
Esta página foi criada como um exemplo inicial para a interface de administração de passageiros.
Ela contém funcionalidades básicas como:
- Listagem de passageiros com dados estáticos
- Modal para adicionar e editar passageiros
- Botões de ação (editar/remover)
- Estilização com Tailwind CSS
- Layout responsivo
⚠️ Importante: Esta não é a versão final da página.
O objetivo deste commit é apenas fornecer uma base visual e funcional para evoluções futuras.  
A versão final pode incluir integração com backend, paginação, validações de formulário e melhorias de acessibilidade.
=> feat(admin): adicionar página de exemplo para gestão de passageiros

frontend/src/app/motorista/page.tsx, frontend/src/app/pessoalmotorista/cadastromotorista/page.tsx, frontend/src/app/usuario/page.tsx
Esta atualização implementa uma série de melhorias nos formulários de cadastro e perfis de usuário/motorista, com foco em usabilidade, consistência de dados e segurança.
As principais mudanças incluem:
- Máscaras de Formatação:
-  Adicionadas máscaras para os campos de Telefone, CNH, CPF e Placa. Isso padroniza a entrada de dados e melhora a
experiência do usuário.
- Melhorias no Cadastro de Motorista:
- O campo CPF foi removido, simplificando o formulário.
- Implementado um indicador de força de senha em tempo real com
critérios de segurança visíveis, guiando o usuário a criar uma
senha mais forte.
- Adicionada a funcionalidade de mostrar/ocultar senha nos campos
de senha e confirmação.
- Incluído um checkbox obrigatório para aceite dos Termos de Serviço.
- Adicionado o campo "Placa" …
=> feat(forms): adiciona máscaras e melhorias de UX em cadastros e perfis

backend/src/main/java/com/borasio_back/backend/controller/ChatController.java, backend/src/main/java/com/borasio_back/backend/controller/PagamentoController.java, backend/src/main/java/com/borasio_back/backend/controller/PasswordRecoveryController.java, backend/src/main/java/com/borasio_back/backend/dto/ChatDTO.java, backend/src/main/java/com/borasio_back/backend/model/entity/Chat.java, backend/src/main/java/com/borasio_back/backend/repository/ChatRepository.java, backend/src/main/java/com/borasio_back/backend/service/ChatService.java, backend/src/main/java/com/borasio_back/backend/service/PagamentoService.java
=> API de pagamento e chat feito

backend/src/main/java/com/borasio_back/backend/dto/ChatMensagemDTO.java, backend/src/main/java/com/borasio_back/backend/service/ChatPublisher.java, backend/src/main/java/com/borasio_back/backend/service/CorridaPublisher.java, backend/src/main/java/com/borasio_back/backend/service/PagamentoPublisher.java, backend/src/main/java/com/borasio_back/backend/service/UsuarioPublisher.java
feat(backend) Arquivos de publisher do RabbitMQ
=> feat(backend) Arquivos de publisher do RabbitMQ

frontend/src/app/components/Header.tsx, frontend/src/app/components/Hero.tsx, frontend/src/app/pessoal/login/page.tsx, frontend/src/app/pessoalmotorista/loginmotorista/page.tsx
- Adicionado botão de sair no Header.tsx para permitir logout do usuário e motorista;
- Corrigido erro de ortografia no componente Hero.tsx.
=> feat(frontend/header): adiciona botão de sair

backend/src/main/java/com/borasio_back/backend/BackendApplication.java, backend/src/main/java/com/borasio_back/backend/controller/UsuarioController.java, backend/src/main/java/com/borasio_back/backend/service/UsuarioService.java, frontend/src/app/corridas/page.tsx, frontend/src/app/pessoal/login/page.tsx, frontend/src/app/pessoalmotorista/loginmotorista/page.tsx
Backend:
- O `UsuarioController` estava tratando `Optional` vazios e retornando um status 404 diretamente. Esse comportamento, embora funcional para o cliente, impedia que a exceção `ResourceNotFoundException` fosse capturada pelo `GlobalExceptionHandler` e, consequentemente, reportada ao Sentry.
- Esta mudança refatora o `UsuarioService` para lançar a `ResourceNotFoundException` em vez de retornar um `Optional`, garantindo que todos os erros de "recurso não encontrado" sejam devidamente registrados como eventos no Sentry, melhorando a observabilidade de erros tratados da aplicação. O `UsuarioController` foi ajustado para se alinhar a esta nova abordagem.
Frontend:
- Adiciona funcionalidade de mostrar/ocultar senha nos formulários de login de passageiro e motorista.  
- Padroniza a paleta …
=> fix(sentry): Garante o reporte de exceções de recurso não encontrado

frontend/src/app/corrida-em-grupo/page.tsx, frontend/src/app/corridas/page.tsx, frontend/src/app/modo-ilha/page.tsx
feat(routes) Alterações em algumas páginas do front-end
=> feat(routes) Alterações em algumas páginas do front-end

frontend/src/app/corrida-em-grupo/page.tsx, frontend/src/app/corridas/page.tsx, frontend/src/app/oferecer-carona/page.tsx
feat(routes) Alterações em algumas páginas do front-end e criação da página oferecer-carona
=> feat(routes) Alterações em algumas páginas do front-end e criação da página oferecer-carona

backend/Dockerfile, frontend/Dockerfile
Atualiza Dockerfiles de front-end e back-end para compilações em vários estágios e opções de tempo de execução
=> chore(docker):atualiza Dockerfiles de front-end e back-end

docker-compose.yml
Atualiza docker-compose com env, healthchecks e políticas de reinicialização
=> chore(docker): atualiza docker-compose

frontend/src/app/components/Acessibilidade.tsx, frontend/src/app/globals.css, frontend/src/app/layout.tsx, frontend/src/app/oferecer-carona/page.tsx, frontend/tsconfig.json
feat(routes) Arquivos do front atualizados
=> feat(routes) Arquivos do front atualizados
